config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:edit, :update]

  resources :contents do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end  
  root "contents#index"
  
  
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :text, presence: true

  def self.search(search)
    if search != ""
      Content.where('text LIKE(?)', "%#{search}%")
    else
      Content.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :name, presence: true, uniqueness: true
  has_many :comments
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @content = Content.find(params[:content_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to content_path(@content), notice: "コメントを入力しました"
    else
      flash.now[:alert] = "失敗しました。再度お試しください"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, content_id: params[:content_id])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @contents = Content.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    @comment = Comment.new
    @comments = @content.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    content = Content.find(params[:id])
    if content.update(content_params)
      redirect_to contents_path(params[:id]), notice: "テキストを変更しました"
    else
      contents = Content.includes(:user)
      flash.now[:alert] = "変更できませんでした。もう一度お試しください"
      render "edit"
    end

  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to contents_path(@content.id), notice: "メッセージが送信されました"
    else
      @contents = Content.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  def destroy
    content = Content.find(params[:id])
    if content.destroy
      redirect_to contents_path(params[:id]), notice: "削除しました"
    else
      flash.now[:alert] = "失敗しました。再度お試しください"
      render :show
    end
  end

  def search
    @contents = Content.search(params[:keyword])
    @keyword = params[:keyword] #検索した文字列を代入
  end

  private

  def content_params
    params.require(:content).permit(:text).merge(user_id: current_user.id)
  end

  def set_content
    @content = Content.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit  
  end

  def update
    if current_user.update(user_params)
       redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_footer.html.haml
.Fotter
  %p.text
    © otyanoma

app/views/contents/_head_bar.html.haml
.Header
  .LeftHeader
    .LeftHeader__Left
      = link_to root_path do
        otyanoma
    .LeftHeader__Right
      - if user_signed_in?
        = link_to edit_user_path(current_user), class: "CurrentUserName" do
          = icon("fa", "user fa-lg")
          = current_user.name
      - else
        = link_to new_user_registration_path , class: "LeftHeader__Right__Btn" do
          新規登録
        = link_to new_user_session_path , class: "LeftHeader__Right__Btn" do
          ログイン
      
  .RightHeader
    .RightHeader__SearchBox
      .RightHeader__SearchBox__Form
        = form_with url: search_contents_path, local: true, method: :get, class: "Form" do |f| 
          = f.text_field :keyword, class: 'InputText', placeholder: 'キーワードから探す'
          %button{type: "submit", class: "SubmitBtn"}
            .RightHeader__SearchBox__Form__Icon
              = icon("fas", "search")
            
    

app/views/contents/_main_content.html.haml
.TopMain
  .FirstView
    = image_tag 'back/kazoku.jpg', alt: '犬の家族', height: '300px', width: '500px'
    %p 介護の疑問・不安を解決しませんか？
  .FirstViewBtn
    - if user_signed_in?
      = link_to("今すぐ介護の相談をする", new_content_path, class: "FirstViewText")
    - else
      = link_to("今すぐ会員登録して相談をする", new_user_registration_path, class: "FirstViewText")

.Middle
  .MiddleBar
    .MiddleBar__Center
      __ 相談、Q&A 
  .Contents
    - @contents.each do |content|
      .ContentsBox
        .UserBox
          .UserBox__Name
            = icon("fa", "user fa-2x")
            = link_to "#", class: "Name" do
              = content.user.name
        .TextBox
          %p.Body
            = link_to content_path(content.id), class: "Body" do
              = content.text
        .DateBox
          %p.NowDate
            = content.created_at.strftime("%Y.%m.%d %H:%M")  
    .Last
      = paginate @contents


    
    
    
    

app/views/contents/edit.html.haml
.ContentSendPage
  = render "head_bar"
  .ContentSend
    .Middle
      .MiddleBar
        .MiddleBar__Center
          __ 編集する
    .ContentSendForm
      .ContentSendName
        = current_user.name
      .ContentSendBox
        = form_with model: @content, class: 'ContentCreateForm', local: true do |f|
          .ContentSendInputText
            = f.text_area :text, class: 'ContentSendInputText__InputText', placeholder: '介護に関してのご質問・ご相談はこちらからご入力ください', rows: '20'
          .ContentSendBtn
            = f.submit '更新する', class: 'ContentSendBtn__SubmitBtn'

  = render "footer"

app/views/contents/index.html.haml
.wrapper
  = render "head_bar"
  = render "main_content"
  = render "footer"

app/views/contents/new.html.haml
.ContentSendPage
  = render "head_bar"
  .ContentSend
    .Middle
      .MiddleBar
        .MiddleBar__Center
          __ 相談、介護に関しての質問をする
    .ContentSendForm
      .ContentSendName
      .ContentSendBox
        = form_with model: @content, class: 'ContentCreateForm', local: true do |f|
          .ContentSendInputText
            = f.text_area :text, class: 'ContentSendInputText__InputText', placeholder: '介護に関してのご質問・ご相談はこちらからご入力ください', rows: '20'
          .ContentSendBtn
            = f.submit '投稿する', class: 'ContentSendBtn__SubmitBtn'

  = render "footer"

app/views/contents/search.html.haml
.SearchContents
  = render "head_bar"
  .Middle
    .MiddleBar
      .MiddleBar__Center
        - if @keyword != ""
          #{@keyword} の検索結果一覧
        - else
          一覧を表示しています
  
    .Contents
      - @contents.each do |content|
        .ContentsBox
          .UserBox
            .UserBox__Name
              = icon("fa", "user fa-2x")
              = link_to "#", class: "Name" do
                = content.user.name
          .TextBox
            %p.Body
              = link_to content_path(content.id), class: "Body" do
                = content.text
          .DateBox
            %p.NowDate
              = content.created_at.strftime("%Y.%m.%d %H:%M")  

app/views/contents/show.html.haml
.ContentDetail
  = render "head_bar"
  
  .TopMain
    .FirstView
      = image_tag 'back/kazoku.jpg', alt: '犬の家族', height: '300px', width: '500px'
      %p 介護の疑問・不安を解決しませんか？
    .FirstViewBtn
      - if user_signed_in?
        = link_to("今すぐ介護の相談をする", new_content_path, class: "FirstViewText")
      - else
        = link_to("今すぐ会員登録して相談をする", new_user_registration_path, class: "FirstViewText")
  
  .Middle
    .MiddleBar
      .MiddleBar__Center
        __ 相談、Q&A

    .ContentsShowBox
      .ContentsMessageBox
        .UserBox
          .UserBox__Name
            = icon("fa", "user fa-2x")
            = link_to "#" , class: "Name" do
              = @content.user.name 
            - if user_signed_in? && @content.user_id == current_user.id
              = link_to edit_content_path(@content.id), class: "EditBtn" do
                = icon("fa", "edit")
              = link_to content_path(@content.id), method: :delete, class: "DeleteBtn", data: { confirm: "本当に削除してもよろしいですか？" }  do
                = icon("fa", "trash-alt")
        .TextBoxShow
          %p.BodyContent
            = simple_format(@content.text)
        .DateBox
          %p.NowDate
            = @content.created_at.strftime("%Y.%m.%d %H:%M") 
  
  .CommentConteiner
    .Middle
      .MiddleBar
        .MiddleBar__Center
          __ 回答一覧
    .CommentForm
      - if user_signed_in?
        = form_with(model: [@content, @comment], class: 'CommnetSend', local: true) do |f|
          = f.text_area :text, class: 'CommnetSend__Form', placeholder: 'コメントを入力する', rows: '3'
          = f.submit 'SEND', class: 'CommnetSend__SubmitBtn'
      - else
        .LoginMessage
          = link_to("※※今すぐ登録してコメントする※※", new_user_registration_path, class: "LoginMessage__Link")
         
    .CommentBox
      - @comments.each do |comment|
        - if comment.user_id == @content.user_id
          .CommentBox__TopUserBox
            .CommentBox__TopUserBox__TopUserName
              = icon("fa", "user fa-2x")
              = link_to "#" , class: "TopName" do
                = comment.user.name
          .TopCommentTextBox
            %p.TopCommentTextBox__TopBody
              = simple_format(comment.text)
          .TopDateRight
            %p.NowDateComment
              = comment.created_at.strftime("%Y.%m.%d %H:%M")

        - else
          .CommentBox__UserBox
            .CommentBox__UserBox__UserName
              = icon("fa", "user fa-2x")
              = link_to "#" , class: "Name" do
                = comment.user.name
          .CommentTextBox
            %p.CommentTextBox__Body
              = simple_format(comment.text)
          .DateRight
            %p.NowDateComment
              = comment.created_at.strftime("%Y.%m.%d %H:%M") 
    
  = render "footer"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Otyanoma
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__Header
    = link_to root_path do
      %h1 アカウント編集
  .AccountPage__Form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :email, "メールアドレス"
          %span 必須 
        .FormField__input--normal
          = f.email_field :email, plaseholder: :email
      .FormField
        .FormField__label--normal
          = f.label :password, "パスワード"
          %i (英数字8文字以上)
          %span 必須
        .FormField__input--normal
          = f.password_field :password, autocomplete: "off"
      .FormField
        .FormField__label--normal
          = f.label :password_confirmation, "パスワード（確認用）"
          %span 必須
        .FormField__input--normal
          = f.password_field :password_confirmation, autocomplete: "off"
      .actions
        = f.submit "変更する", class: 'Button UserButton'
  .AccountPage__toLoginOrSignIn
    %p ログアウトする方はこちら
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'